import { t } from "i18next";

export const userColumns = [
  { field: "id", headerName: "ID", width: 70 },
  {
    field: "user",
    headerName: "User",
    width: 230,
    renderCell: (params) => {
      return (
        <div className="cellWithImg">
          <img className="cellImg" src={params.row.img} alt="avatar" />
          {params.row.username}
        </div>
      );
    },
  },
  {
    field: "email",
    headerName: "Email",
    width: 230,
  },

  {
    field: "designation",
    headerName: t("datatable.designation"),
    width: 100,
  },
  {
    field: "status",
    headerName: "Status",
    width: 160,
    renderCell: (params) => {
      return (
        <div className={`cellWithStatus ${params.row.status}`}>
          {params.row.status}
        </div>
      );
    },
  },
];

//temporary data
export const userRows = [
  {
    id: 1,
    username: "Snow",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    status: "active",
    email: "1snow@gmail.com",
    designation: 35,
  },
  {
    id: 2,
    username: "Jamie Lannister",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "2snow@gmail.com",
    status: "passive",
    designation: 42,
  },
  {
    id: 3,
    username: "Lannister",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "3snow@gmail.com",
    status: "pending",
    designation: 45,
  },
  {
    id: 4,
    username: "Stark",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "4snow@gmail.com",
    status: "active",
    designation: 16,
  },
  {
    id: 5,
    username: "Targaryen",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "5snow@gmail.com",
    status: "passive",
    designation: 22,
  },
  {
    id: 6,
    username: "Melisandre",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "6snow@gmail.com",
    status: "active",
    designation: 15,
  },
  {
    id: 7,
    username: "Clifford",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "7snow@gmail.com",
    status: "passive",
    designation: 44,
  },
  {
    id: 8,
    username: "Frances",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "8snow@gmail.com",
    status: "active",
    designation: 36,
  },
  {
    id: 9,
    username: "Roxie",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "snow@gmail.com",
    status: "pending",
    designation: 65,
  },
  {
    id: 10,
    username: "Roxie",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "snow@gmail.com",
    status: "active",
    designation: 65,
  },
];

export const kladerColumns = [
  { field: "id", headerName: "ID", width: 70 },
  { field: "name", headerName: "Name", width: 200 },
  { field: "address", headerName: "Address", width: 250 },
  { field: "phone", headerName: "Phone", width: 150 },
  { field: "email", headerName: "Email", width: 200 },
];

export const kladerRows = [
  {
    id: 1,
    name: "John Doe",
    address: "123 Main St, Anytown, USA",
    phone: "123-456-7890",
    email: "johndoe@example.com",
  },
  {
    id: 2,
    name: "Jane Smith",
    address: "456 Elm St, Othertown, USA",
    phone: "987-654-3210",
    email: "janesmith@example.com",
  },
  {
    id: 3,
    name: "Sam Johnson",
    address: "789 Oak St, Newtown, USA",
    phone: "555-123-4567",
    email: "samjohnson@example.com",
  },
  {
    id: 4,
    name: "Emily Brown",
    address: "321 Pine St, Somewhere, USA",
    phone: "222-333-4444",
    email: "emilybrown@example.com",
  },
  {
    id: 5,
    name: "Michael Davis",
    address: "567 Maple St, Elsewhere, USA",
    phone: "777-888-9999",
    email: "michaeldavis@example.com",
  },
  {
    id: 6,
    name: "Sara Wilson",
    address: "890 Cedar St, Anotherplace, USA",
    phone: "111-222-3333",
    email: "sarawilson@example.com",
  },
  {
    id: 7,
    name: "David Miller",
    address: "654 Birch St, Here, USA",
    phone: "444-555-6666",
    email: "davidmiller@example.com",
  },
  {
    id: 8,
    name: "Anna Thompson",
    address: "876 Oak St, Nowhere, USA",
    phone: "999-888-7777",
    email: "annathompson@example.com",
  },
  {
    id: 9,
    name: "Robert Lee",
    address: "741 Elm St, Anywhere, USA",
    phone: "333-222-1111",
    email: "robertlee@example.com",
  },
  {
    id: 10,
    name: "Jessica Martinez",
    address: "963 Pine St, Everywhere, USA",
    phone: "666-777-8888",
    email: "jessicamartinez@example.com",
  },
  {
    id: 11,
    name: "Kevin Clark",
    address: "852 Maple St, Somewhereelse, USA",
    phone: "111-333-5555",
    email: "kevinclark@example.com",
  },
  {
    id: 12,
    name: "Linda Harris",
    address: "159 Cedar St, Anotherwhere, USA",
    phone: "777-999-1111",
    email: "lindaharris@example.com",
  },
];

export const companyColumns = [
  { field: "id", headerName: "ID", width: 70 },
  { field: "companyName", headerName: "Company Name", width: 200 },
  { field: "industry", headerName: "Industry", width: 150 },
  { field: "city", headerName: "City", width: 120 },
  { field: "country", headerName: "Country", width: 120 },
];

export const companyRows = [
  {
    id: 1,
    companyName: "Example Company 1",
    companyRegistrationNumber: "123456789",
    industry: "Technology",
    website: "https://example.com",
    description: "Example Company Description 1",
    contactName: "John Doe",
    contactEmail: "john.doe@example.com",
    contactPhone: "123-456-7890",
    address: "123 Example St",
    city: "Exampleville",
    state: "Ex",
    postalCode: "12345",
    country: "Exampleland",
    employees: "100",
    yearFounded: "2000",
    revenue: "1000000",
    email: "john.doe@example.com",
    terms: true,
  },
  {
    id: 2,
    companyName: "Example Company 2",
    companyRegistrationNumber: "987654321",
    industry: "Finance",
    website: "https://example.org",
    description: "Example Company Description 2",
    contactName: "Jane Smith",
    contactEmail: "jane.smith@example.com",
    contactPhone: "987-654-3210",
    address: "456 Sample St",
    city: "Samplington",
    state: "Sa",
    postalCode: "54321",
    country: "Sampland",
    employees: "50",
    yearFounded: "1990",
    revenue: "500000",
    email: "jane.smith@example.com",
    terms: true,
  },
  {
    id: 3,
    companyName: "Example Company 3",
    companyRegistrationNumber: "555555555",
    industry: "Healthcare",
    website: "https://example.org",
    description: "Example Company Description 3",
    contactName: "David Brown",
    contactEmail: "david.brown@example.com",
    contactPhone: "555-555-5555",
    address: "789 Elm St",
    city: "Elmsville",
    state: "El",
    postalCode: "67890",
    country: "Elmland",
    employees: "200",
    yearFounded: "2010",
    revenue: "2000000",
    email: "david.brown@example.com",
    terms: true,
  },
  {
    id: 4,
    companyName: "Example Company 4",
    companyRegistrationNumber: "111111111",
    industry: "Education",
    website: "https://example.org",
    description: "Example Company Description 4",
    contactName: "Sarah Johnson",
    contactEmail: "sarah.johnson@example.com",
    contactPhone: "111-111-1111",
    address: "321 Oak St",
    city: "Oaktown",
    state: "Ok",
    postalCode: "54321",
    country: "Oakland",
    employees: "300",
    yearFounded: "2005",
    revenue: "1500000",
    email: "sarah.johnson@example.com",
    terms: true,
  },
  {
    id: 5,
    companyName: "Example Company 5",
    companyRegistrationNumber: "999999999",
    industry: "Retail",
    website: "https://example.org",
    description: "Example Company Description 5",
    contactName: "Michael Wilson",
    contactEmail: "michael.wilson@example.com",
    contactPhone: "999-999-9999",
    address: "567 Pine St",
    city: "Pinetown",
    state: "Pi",
    postalCode: "98765",
    country: "Pineland",
    employees: "150",
    yearFounded: "1995",
    revenue: "800000",
    email: "michael.wilson@example.com",
    terms: true,
  },
  {
    id: 6,
    companyName: "Example Company 6",
    companyRegistrationNumber: "777777777",
    industry: "Automotive",
    website: "https://example.org",
    description: "Example Company Description 6",
    contactName: "Emily Davis",
    contactEmail: "emily.davis@example.com",
    contactPhone: "777-777-7777",
    address: "890 Maple St",
    city: "Mapleton",
    state: "Ma",
    postalCode: "34567",
    country: "Mapland",
    employees: "75",
    yearFounded: "2003",
    revenue: "600000",
    email: "emily.davis@example.com",
    terms: true,
  },
  {
    id: 7,
    companyName: "Example Company 7",
    companyRegistrationNumber: "444444444",
    industry: "Consulting",
    website: "https://example.org",
    description: "Example Company Description 7",
    contactName: "Jason White",
    contactEmail: "jason.white@example.com",
    contactPhone: "444-444-4444",
    address: "741 Cedar St",
    city: "Cedartown",
    state: "Ce",
    postalCode: "23456",
    country: "Cedarland",
    employees: "250",
    yearFounded: "2012",
    revenue: "1800000",
    email: "jason.white@example.com",
    terms: true,
  },
  {
    id: 8,
    companyName: "Example Company 8",
    companyRegistrationNumber: "666666666",
    industry: "Media",
    website: "https://example.org",
    description: "Example Company Description 8",
    contactName: "Michelle Garcia",
    contactEmail: "michelle.garcia@example.com",
    contactPhone: "666-666-6666",
    address: "852 Birch St",
    city: "Birchville",
    state: "Bi",
    postalCode: "45678",
    country: "Birchland",
    employees: "120",
    yearFounded: "2007",
    revenue: "900000",
    email: "michelle.garcia@example.com",
    terms: true,
  },
  {
    id: 9,
    companyName: "Example Company 9",
    companyRegistrationNumber: "222222222",
    industry: "Real Estate",
    website: "https://example.org",
    description: "Example Company Description 9",
    contactName: "Daniel Martinez",
    contactEmail: "daniel.martinez@example.com",
    contactPhone: "222-222-2222",
    address: "963 Elm St",
    city: "Elmtown",
    state: "El",
    postalCode: "56789",
    country: "Elmland",
    employees: "80",
    yearFounded: "2015",
    revenue: "700000",
    email: "daniel.martinez@example.com",
    terms: true,
  },
  {
    id: 10,
    companyName: "Example Company 10",
    companyRegistrationNumber: "888888888",
    industry: "Food & Beverage",
    website: "https://example.org",
    description: "Example Company Description 10",
    contactName: "Laura Brown",
    contactEmail: "laura.brown@example.com",
    contactPhone: "888-888-8888",
    address: "159 Oak St",
    city: "Oaktown",
    state: "Ok",
    postalCode: "67890",
    country: "Oakland",
    employees: "95",
    yearFounded: "2018",
    revenue: "400000",
    email: "laura.brown@example.com",
    terms: true,
  },
  {
    id: 11,
    companyName: "Example Company 11",
    companyRegistrationNumber: "333333333",
    industry: "Energy",
    website: "https://example.org",
    description: "Example Company Description 11",
    contactName: "Christopher Wilson",
    contactEmail: "christopher.wilson@example.com",
    contactPhone: "333-333-3333",
    address: "456 Maple St",
    city: "Mapleville",
    state: "Ma",
    postalCode: "45678",
    country: "Mapland",
    employees: "180",
    yearFounded: "2009",
    revenue: "1200000",
    email: "christopher.wilson@example.com",
    terms: true,
  },
  {
    id: 12,
    companyName: "Example Company 12",
    companyRegistrationNumber: "555555555",
    industry: "Telecommunications",
    website: "https://example.org",
    description: "Example Company Description 12",
    contactName: "Sophia Lee",
    contactEmail: "sophia.lee@example.com",
    contactPhone: "555-555-5555",
    address: "789 Cedar St",
    city: "Cedartown",
    state: "Ce",
    postalCode: "23456",
    country: "Cedarland",
    employees: "220",
    yearFounded: "2011",
    revenue: "1600000",
    email: "sophia.lee@example.com",
    terms: true,
  },
];

export const associationColumns = [
  { field: "id", headerName: "ID", width: 70 },
  { field: "associationName", headerName: "Association Name", width: 200 },
  {
    field: "registrationNumber",
    headerName: "Registration Number",
    width: 150,
  },
  { field: "industry", headerName: "Industry", width: 130 },
  { field: "contactName", headerName: "Contact Name", width: 150 },
  { field: "contactEmail", headerName: "Contact Email", width: 200 },
  { field: "contactPhone", headerName: "Contact Phone", width: 150 },
  { field: "numberOfMembers", headerName: "Number of Members", width: 150 },
];
export const associationRows = [
  {
    id: 1,
    associationName: "Example Association 1",
    registrationNumber: "123456789",
    industry: "Non-profit",
    contactName: "John Doe",
    contactEmail: "john.doe@example.com",
    contactPhone: "123-456-7890",
    numberOfMembers: "1000",
  },
  {
    id: 2,
    associationName: "Example Association 2",
    registrationNumber: "987654321",
    industry: "Non-profit",
    contactName: "Jane Smith",
    contactEmail: "jane.smith@example.com",
    contactPhone: "987-654-3210",
    numberOfMembers: "1500",
  },
  {
    id: 3,
    associationName: "Example Association 3",
    registrationNumber: "234567891",
    industry: "Non-profit",
    contactName: "Alice Johnson",
    contactEmail: "alice.johnson@example.com",
    contactPhone: "345-678-9012",
    numberOfMembers: "1200",
  },
  {
    id: 4,
    associationName: "Example Association 4",
    registrationNumber: "345678912",
    industry: "Non-profit",
    contactName: "Bob Brown",
    contactEmail: "bob.brown@example.com",
    contactPhone: "456-789-0123",
    numberOfMembers: "1100",
  },
  {
    id: 5,
    associationName: "Example Association 5",
    registrationNumber: "456789123",
    industry: "Non-profit",
    contactName: "Charlie Davis",
    contactEmail: "charlie.davis@example.com",
    contactPhone: "567-890-1234",
    numberOfMembers: "1300",
  },
  {
    id: 6,
    associationName: "Example Association 6",
    registrationNumber: "567891234",
    industry: "Non-profit",
    contactName: "David Evans",
    contactEmail: "david.evans@example.com",
    contactPhone: "678-901-2345",
    numberOfMembers: "1400",
  },
  {
    id: 7,
    associationName: "Example Association 7",
    registrationNumber: "678912345",
    industry: "Non-profit",
    contactName: "Eve Foster",
    contactEmail: "eve.foster@example.com",
    contactPhone: "789-012-3456",
    numberOfMembers: "1150",
  },
  {
    id: 8,
    associationName: "Example Association 8",
    registrationNumber: "789123456",
    industry: "Non-profit",
    contactName: "Frank Green",
    contactEmail: "frank.green@example.com",
    contactPhone: "890-123-4567",
    numberOfMembers: "1250",
  },
  {
    id: 9,
    associationName: "Example Association 9",
    registrationNumber: "891234567",
    industry: "Non-profit",
    contactName: "Grace Hill",
    contactEmail: "grace.hill@example.com",
    contactPhone: "901-234-5678",
    numberOfMembers: "1350",
  },
  {
    id: 10,
    associationName: "Example Association 10",
    registrationNumber: "912345678",
    industry: "Non-profit",
    contactName: "Henry Irvine",
    contactEmail: "henry.irvine@example.com",
    contactPhone: "012-345-6789",
    numberOfMembers: "1050",
  },
  {
    id: 11,
    associationName: "Example Association 11",
    registrationNumber: "123456780",
    industry: "Non-profit",
    contactName: "Isla Jackson",
    contactEmail: "isla.jackson@example.com",
    contactPhone: "123-456-7800",
    numberOfMembers: "1450",
  },
  {
    id: 12,
    associationName: "Example Association 12",
    registrationNumber: "234567801",
    industry: "Non-profit",
    contactName: "Jack King",
    contactEmail: "jack.king@example.com",
    contactPhone: "234-567-8012",
    numberOfMembers: "1550",
  },
];

export const expertiseColumns = [
  { field: "id", headerName: "ID", width: 70 },
  { field: "biography", headerName: "Biography", width: 200 },
  { field: "companyName", headerName: "Company Name", width: 150 },
  { field: "address", headerName: "Address", width: 200 },
  { field: "website", headerName: "Website", width: 150 },
  { field: "email", headerName: "Email", width: 200 },
  { field: "phoneNumber", headerName: "Phone Number", width: 150 },
  { field: "sirenNumber", headerName: "Siren Number", width: 150 },
];

export const expertiseRows = [
  {
    id: 1,
    biography: "Expert in software development",
    companyName: "Tech Solutions",
    address: "123 Tech St",
    website: "https://techsolutions.com",
    email: "info@techsolutions.com",
    phoneNumber: "123-456-7890",
    sirenNumber: "123456789",
  },
  {
    id: 2,
    biography: "Experienced web developer",
    companyName: "WebWorks",
    address: "456 Web Ave",
    website: "https://webworks.com",
    email: "contact@webworks.com",
    phoneNumber: "234-567-8901",
    sirenNumber: "987654321",
  },
  {
    id: 3,
    biography: "Specialist in AI and ML",
    companyName: "AI Innovators",
    address: "789 AI Blvd",
    website: "https://aiinnovators.com",
    email: "support@aiinnovators.com",
    phoneNumber: "345-678-9012",
    sirenNumber: "456123789",
  },
  {
    id: 4,
    biography: "Expert in data science",
    companyName: "Data Insights",
    address: "101 Data Rd",
    website: "https://datainsights.com",
    email: "info@datainsights.com",
    phoneNumber: "456-789-0123",
    sirenNumber: "789456123",
  },
  {
    id: 5,
    biography: "Cloud computing specialist",
    companyName: "Cloud Solutions",
    address: "202 Cloud Way",
    website: "https://cloudsolutions.com",
    email: "contact@cloudsolutions.com",
    phoneNumber: "567-890-1234",
    sirenNumber: "321654987",
  },
  {
    id: 6,
    biography: "Cybersecurity expert",
    companyName: "SecureTech",
    address: "303 Secure St",
    website: "https://securetech.com",
    email: "support@securetech.com",
    phoneNumber: "678-901-2345",
    sirenNumber: "654987321",
  },
  {
    id: 7,
    biography: "Mobile app developer",
    companyName: "App Makers",
    address: "404 App Ln",
    website: "https://appmakers.com",
    email: "info@appmakers.com",
    phoneNumber: "789-012-3456",
    sirenNumber: "123789456",
  },
  {
    id: 8,
    biography: "Blockchain technology expert",
    companyName: "Blockchain Corp",
    address: "505 Blockchain Rd",
    website: "https://blockchaincorp.com",
    email: "contact@blockchaincorp.com",
    phoneNumber: "890-123-4567",
    sirenNumber: "987321654",
  },
  {
    id: 9,
    biography: "Big data specialist",
    companyName: "Big Data Inc",
    address: "606 Data St",
    website: "https://bigdatainc.com",
    email: "info@bigdatainc.com",
    phoneNumber: "901-234-5678",
    sirenNumber: "321987654",
  },
  {
    id: 10,
    biography: "E-commerce solutions expert",
    companyName: "E-Shop Experts",
    address: "707 Commerce St",
    website: "https://eshopexperts.com",
    email: "support@eshopexperts.com",
    phoneNumber: "012-345-6789",
    sirenNumber: "654321987",
  },
  {
    id: 11,
    biography: "IT infrastructure specialist",
    companyName: "InfraTech",
    address: "808 Infra Ave",
    website: "https://infratech.com",
    email: "contact@infratech.com",
    phoneNumber: "123-456-7891",
    sirenNumber: "987654123",
  },
  {
    id: 12,
    biography: "Digital marketing expert",
    companyName: "Marketing Gurus",
    address: "909 Market St",
    website: "https://marketinggurus.com",
    email: "info@marketinggurus.com",
    phoneNumber: "234-567-8902",
    sirenNumber: "123456321",
  },
];

export const groupColumns = [
  { field: "id", headerName: "ID", width: 70 },
  { field: "groupName", headerName: "Group Name", width: 150 },
  { field: "fieldOfActivity", headerName: "Field of Activity", width: 150 },
  { field: "subscription", headerName: "Subscription", width: 120 },
  { field: "email", headerName: "Email", width: 200 },
  { field: "phoneNumber", headerName: "Phone Number", width: 150 },
];
export const groupRows = [
  {
    id: 1,
    groupName: "Education Alliance",
    fieldOfActivity: "Education",
    subscription: "Paid",
    email: "contact@educationalliance.com",
    phoneNumber: "123-456-7890",
  },
  {
    id: 2,
    groupName: "Healthcare Group",
    fieldOfActivity: "Healthcare",
    subscription: "Free",
    email: "info@healthcaregroup.com",
    phoneNumber: "234-567-8901",
  },
  {
    id: 3,
    groupName: "Tech Innovators",
    fieldOfActivity: "Technology",
    subscription: "Paid",
    email: "support@techinnovators.com",
    phoneNumber: "345-678-9012",
  },
  {
    id: 4,
    groupName: "Green Earth",
    fieldOfActivity: "Environment",
    subscription: "Paid",
    email: "hello@greenearth.com",
    phoneNumber: "456-789-0123",
  },
  {
    id: 5,
    groupName: "Art Enthusiasts",
    fieldOfActivity: "Arts",
    subscription: "Free",
    email: "contact@artenthusiasts.com",
    phoneNumber: "567-890-1234",
  },
  {
    id: 6,
    groupName: "Sports Fans",
    fieldOfActivity: "Sports",
    subscription: "Paid",
    email: "info@sportsfans.com",
    phoneNumber: "678-901-2345",
  },
  {
    id: 7,
    groupName: "Music Lovers",
    fieldOfActivity: "Music",
    subscription: "Free",
    email: "support@musiclovers.com",
    phoneNumber: "789-012-3456",
  },
  {
    id: 8,
    groupName: "Business Network",
    fieldOfActivity: "Business",
    subscription: "Paid",
    email: "hello@businessnetwork.com",
    phoneNumber: "890-123-4567",
  },
  {
    id: 9,
    groupName: "Travel Community",
    fieldOfActivity: "Travel",
    subscription: "Free",
    email: "contact@travelcommunity.com",
    phoneNumber: "901-234-5678",
  },
  {
    id: 10,
    groupName: "Foodies Club",
    fieldOfActivity: "Food",
    subscription: "Paid",
    email: "info@foodiesclub.com",
    phoneNumber: "012-345-6789",
  },
  {
    id: 11,
    groupName: "Fitness Buffs",
    fieldOfActivity: "Fitness",
    subscription: "Free",
    email: "support@fitnessbuffs.com",
    phoneNumber: "123-456-7891",
  },
  {
    id: 12,
    groupName: "Book Lovers",
    fieldOfActivity: "Literature",
    subscription: "Paid",
    email: "hello@booklovers.com",
    phoneNumber: "234-567-8902",
  },
];
